import React, { useState } from 'react';
import { FileText, Printer, Copy, Download, ShieldAlert, CheckCircle2, AlertTriangle, Check, Share2, Image as ImageIcon } from 'lucide-react';
import { motion } from 'motion/react';
import { AnalysisResult } from '../types';
import PageHeader from '../components/common/PageHeader';
import Badge, { BadgeVariant } from '../components/common/Badge';
import ShareExportModal from '../components/ShareExportModal';
import { generateMarkdownReport, downloadBlob } from '../utils/exportUtils';

interface ReportViewProps {
  analysis: AnalysisResult | null;
}

export default function ReportView({ analysis }: ReportViewProps) {
  const [copied, setCopied] = useState(false);
  const [isShareModalOpen, setIsShareModalOpen] = useState(false);

  if (!analysis) {
    return (
      <div className="p-12 text-center text-zinc-400 font-mono text-xs">
        No review report available. Please upload a repository first.
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownReport(analysis);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 sm:p-8 max-w-5xl mx-auto space-y-7 select-none font-sans print:p-0 print:bg-white print:text-black">
      {/* Header Actions */}
      <PageHeader
        title="Executive Code Audit Report"
        subtitle="Auditable technical summary for engineering leadership, stakeholders, and compliance"
        icon={<FileText size={22} />}
        className="print:hidden"
        actions={
          <div className="flex items-center space-x-2.5">
            <button
              onClick={() => setIsShareModalOpen(true)}
              className="px-4 py-2 rounded-xl bg-zinc-900 border border-zinc-700 hover:border-zinc-500 hover:bg-zinc-800 text-zinc-200 font-semibold text-xs flex items-center space-x-1.5 transition-all shadow-md cursor-pointer"
            >
              <Share2 size={14} className="text-indigo-400" />
              <span>Share & Export</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs flex items-center space-x-1.5 transition-all shadow-md shadow-indigo-600/20 cursor-pointer"
            >
              <Printer size={14} />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="px-4 py-2 rounded-xl bg-zinc-900 border border-zinc-800 hover:border-zinc-700 text-zinc-300 text-xs font-semibold flex items-center space-x-1.5 transition-colors cursor-pointer"
            >
              {copied ? (
                <>
                  <Check size={14} className="text-emerald-400" />
                  <span className="text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy size={14} />
                  <span>Copy Markdown</span>
                </>
              )}
            </button>
          </div>
        }
      />

      {/* Report Document Sheet */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.25 }}
        className="bg-zinc-900/90 border border-zinc-800/90 rounded-2xl p-8 space-y-8 shadow-2xl print:border-none print:shadow-none print:p-0 backdrop-blur-sm"
      >
        {/* Document Title Banner */}
        <div className="flex items-center justify-between pb-6 border-b border-zinc-800">
          <div>
            <div className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest font-mono">
              CONFIDENTIAL AUDIT SPECIFICATION
            </div>
            <h2 className="text-2xl font-bold text-white mt-1">{analysis.projectName}</h2>
            <p className="text-xs text-zinc-400 mt-0.5">
              Generated by Colens AI • {new Date(analysis.analyzedAt).toLocaleDateString()}
            </p>
          </div>

          <div className="text-right font-mono">
            <div className="text-3xl font-extrabold text-indigo-400">{analysis.scores.overall} / 100</div>
            <div className="text-[10px] font-bold text-zinc-500 uppercase">Health Rating</div>
          </div>
        </div>

        {/* Executive Summary Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 bg-zinc-950/80 rounded-xl border border-zinc-800 font-mono">
            <div className="text-[10px] text-zinc-500 uppercase font-bold">Security</div>
            <div className="text-xl font-bold text-rose-400 mt-1">{analysis.scores.security} / 100</div>
          </div>

          <div className="p-4 bg-zinc-950/80 rounded-xl border border-zinc-800 font-mono">
            <div className="text-[10px] text-zinc-500 uppercase font-bold">Reliability</div>
            <div className="text-xl font-bold text-emerald-400 mt-1">{analysis.scores.reliability} / 100</div>
          </div>

          <div className="p-4 bg-zinc-950/80 rounded-xl border border-zinc-800 font-mono">
            <div className="text-[10px] text-zinc-500 uppercase font-bold">Performance</div>
            <div className="text-xl font-bold text-amber-400 mt-1">{analysis.scores.performance} / 100</div>
          </div>

          <div className="p-4 bg-zinc-950/80 rounded-xl border border-zinc-800 font-mono">
            <div className="text-[10px] text-zinc-500 uppercase font-bold">Maintainability</div>
            <div className="text-xl font-bold text-indigo-400 mt-1">{analysis.scores.maintainability} / 100</div>
          </div>
        </div>

        {/* Key Critical Vulnerabilities Section */}
        <div className="space-y-4">
          <h3 className="font-bold text-white text-sm uppercase tracking-wider font-mono">
            Critical Risk Findings ({analysis.issues.filter((i) => i.severity === 'critical').length})
          </h3>

          <div className="space-y-3 font-sans text-xs">
            {analysis.issues
              .filter((i) => i.severity === 'critical' || i.severity === 'high')
              .map((issue) => (
                <div key={issue.id} className="p-4 rounded-xl bg-zinc-950/80 border border-zinc-800/80 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-rose-400">{issue.title}</span>
                    <span className="font-mono text-zinc-500">{issue.file}:{issue.line}</span>
                  </div>
                  <p className="text-zinc-300 text-[11px] leading-relaxed">{issue.description}</p>
                </div>
              ))}
          </div>
        </div>

        {/* Technical Debt Assessment */}
        <div className="p-5 bg-zinc-950/80 rounded-xl border border-zinc-800/90 space-y-2 text-xs">
          <div className="font-bold text-indigo-400 uppercase font-mono">Technical Debt Assessment</div>
          <p className="text-zinc-300 leading-relaxed font-sans">
            Estimated remediation effort: <span className="font-bold text-white font-mono">1.5 Engineering Days</span> to address all critical vulnerabilities and refactor SQL parameterization.
          </p>
        </div>
      </motion.div>

      {/* Share & Export Modal */}
      <ShareExportModal
        isOpen={isShareModalOpen}
        onClose={() => setIsShareModalOpen(false)}
        analysis={analysis}
      />
    </div>
  );
}
