import React, { useState, useEffect } from 'react';
import { 
  GitPullRequest, 
  GitBranch, 
  CheckCircle2, 
  AlertCircle, 
  ExternalLink, 
  Sparkles, 
  FileCode, 
  ArrowRight, 
  Lock, 
  Github,
  Key,
  Copy,
  Check
} from 'lucide-react';
import Modal from './common/Modal';
import { useGitHub } from '../context/GitHubContext';
import { pushFixToGitHub } from '../services/githubService';
import { Project } from '../types';

interface GitHubPushModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: Project | null;
  filesToCommit: { path: string; content: string }[];
  issueContext?: {
    id: string;
    title: string;
    cwe?: string;
    file: string;
  };
}

export default function GitHubPushModal({
  isOpen,
  onClose,
  project,
  filesToCommit,
  issueContext
}: GitHubPushModalProps) {
  const { user, token, isAuthenticated, loginWithOAuth } = useGitHub();

  // Parse repo owner/name if available from project
  const [repoOwner, setRepoOwner] = useState('');
  const [repoName, setRepoName] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [targetBranch, setTargetBranch] = useState('');
  const [commitMessage, setCommitMessage] = useState('');
  const [createPR, setCreatePR] = useState(true);
  const [prTitle, setPrTitle] = useState('');
  const [prBody, setPrBody] = useState('');

  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [resultData, setResultData] = useState<{
    branch?: string;
    pullRequestUrl?: string;
    pullRequestNumber?: number;
    commitUrl?: string;
    message?: string;
  } | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedLink, setCopiedLink] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      setStatus('idle');
      setErrorMessage(null);
      setResultData(null);
      return;
    }

    // Initialize defaults based on project or user
    let defaultOwner = user?.login || '';
    let defaultRepo = project?.name || 'my-repository';

    // If project description has imported from format: "Imported from GitHub: owner/repo"
    if (project?.description?.includes('Imported from GitHub:')) {
      const match = project.description.match(/Imported from GitHub:\s*([^/]+)\/([^\s(]+)/);
      if (match) {
        defaultOwner = match[1];
        defaultRepo = match[2];
      }
    }

    const branchSlug = issueContext
      ? `colens/fix-${issueContext.id.toLowerCase().replace(/[^a-z0-9]/g, '-')}`
      : `colens/patch-${Date.now().toString(36)}`;

    const title = issueContext
      ? `🛡️ Fix: ${issueContext.title} ${issueContext.cwe ? `(${issueContext.cwe})` : ''}`
      : `🛡️ Apply automated security and architecture fixes`;

    const body = `### 🤖 Colens AI Automated Remediation

This Pull Request was automatically generated by **Colens AI** to fix detected security vulnerabilities and architecture bottlenecks.

#### 📝 Summary of Changes:
- **Target File(s)**: ${filesToCommit.map(f => `\`${f.path}\``).join(', ')}
${issueContext ? `- **Issue**: ${issueContext.title}\n- **CWE**: ${issueContext.cwe || 'N/A'}` : ''}
- **Remediation**: Replaced vulnerable pattern with verified parameterization and defensive checks.

---
*Reviewed and verified with Colens AI Engine.*`;

    setRepoOwner(defaultOwner);
    setRepoName(defaultRepo);
    setBaseBranch('main');
    setTargetBranch(branchSlug);
    setCommitMessage(title);
    setPrTitle(title);
    setPrBody(body);
  }, [isOpen, project, user, issueContext, filesToCommit]);

  const handlePush = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token) return;

    setStatus('loading');
    setErrorMessage(null);

    try {
      const result = await pushFixToGitHub(
        {
          owner: repoOwner.trim(),
          repo: repoName.trim(),
          baseBranch: baseBranch.trim(),
          targetBranch: targetBranch.trim(),
          commitMessage: commitMessage.trim(),
          createPullRequest: createPR,
          prTitle: prTitle.trim(),
          prBody: prBody.trim(),
          changes: filesToCommit
        },
        token
      );

      if (result.success) {
        setStatus('success');
        setResultData({
          branch: result.branch,
          pullRequestUrl: result.pullRequestUrl,
          pullRequestNumber: result.pullRequestNumber,
          commitUrl: result.commitUrl,
          message: result.message
        });
      } else {
        throw new Error(result.error || 'Failed to push commit');
      }
    } catch (err: any) {
      console.error('Push Fix Error:', err);
      setStatus('error');
      setErrorMessage(err.message || 'Failed to push code fix to GitHub.');
    }
  };

  const handleCopyPrLink = () => {
    if (resultData?.pullRequestUrl) {
      navigator.clipboard.writeText(resultData.pullRequestUrl);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      maxWidth="2xl"
      title={
        <div className="flex items-center space-x-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/30 text-indigo-500 flex items-center justify-center">
            <GitPullRequest size={18} />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Push Fix & Open Pull Request
            </h3>
            <p className="text-xs text-slate-500 dark:text-zinc-400">
              Commit automated AI patches directly to your GitHub repository
            </p>
          </div>
        </div>
      }
    >
      {!isAuthenticated ? (
        <div className="text-center py-6 space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-zinc-100 dark:bg-zinc-800 text-slate-900 dark:text-white flex items-center justify-center mx-auto">
            <Github size={24} />
          </div>
          <div className="space-y-1">
            <h4 className="text-sm font-bold text-slate-900 dark:text-white">
              GitHub Authentication Required
            </h4>
            <p className="text-xs text-slate-500 dark:text-zinc-400 max-w-md mx-auto">
              Please connect your GitHub account with <code className="font-mono text-indigo-500">repo</code> write scope to push branches and open Pull Requests.
            </p>
          </div>
          <button
            onClick={() => loginWithOAuth()}
            className="px-5 py-2.5 rounded-xl bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-xs font-bold inline-flex items-center space-x-2 shadow-md hover:scale-102 transition-transform cursor-pointer"
          >
            <Github size={15} />
            <span>Connect GitHub Account</span>
          </button>
        </div>
      ) : status === 'success' && resultData ? (
        <div className="space-y-5 py-2">
          <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-700 dark:text-emerald-300 flex items-start space-x-3">
            <CheckCircle2 size={22} className="text-emerald-500 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                Patches Successfully Pushed to GitHub!
              </h4>
              <p className="text-xs leading-relaxed text-slate-600 dark:text-zinc-300">
                Created branch <code className="font-mono font-semibold bg-emerald-500/10 px-1.5 py-0.5 rounded text-emerald-600 dark:text-emerald-400">{resultData.branch}</code> and committed {filesToCommit.length} modified file(s).
              </p>
            </div>
          </div>

          {resultData.pullRequestUrl && (
            <div className="p-4 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-700 dark:text-zinc-300 flex items-center space-x-1.5">
                  <GitPullRequest size={14} className="text-indigo-500" />
                  <span>Pull Request #{resultData.pullRequestNumber} Created</span>
                </span>
                <button
                  onClick={handleCopyPrLink}
                  className="text-xs text-indigo-600 dark:text-indigo-400 hover:underline flex items-center space-x-1 cursor-pointer font-mono"
                >
                  {copiedLink ? <Check size={12} className="text-emerald-500" /> : <Copy size={12} />}
                  <span>{copiedLink ? 'Copied' : 'Copy Link'}</span>
                </button>
              </div>

              <a
                href={resultData.pullRequestUrl}
                target="_blank"
                rel="noreferrer"
                className="w-full py-2.5 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs flex items-center justify-center space-x-2 transition-all shadow-md cursor-pointer"
              >
                <span>View Pull Request on GitHub</span>
                <ExternalLink size={14} />
              </a>
            </div>
          )}

          <div className="flex justify-end pt-2">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-zinc-800 hover:bg-slate-200 dark:hover:bg-zinc-700 text-slate-800 dark:text-zinc-200 text-xs font-semibold transition-colors cursor-pointer"
            >
              Done
            </button>
          </div>
        </div>
      ) : (
        <form onSubmit={handlePush} className="space-y-4">
          {errorMessage && (
            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-start space-x-2">
              <AlertCircle size={16} className="shrink-0 mt-0.5" />
              <span>{errorMessage}</span>
            </div>
          )}

          {/* Files to commit preview */}
          <div className="p-3 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 space-y-2">
            <div className="text-[11px] font-semibold text-slate-500 dark:text-zinc-400 uppercase tracking-wider font-mono flex items-center justify-between">
              <span>Files with AI Remediation ({filesToCommit.length})</span>
              <span className="text-emerald-600 dark:text-emerald-400 text-[10px]">Ready to commit</span>
            </div>
            <div className="space-y-1 max-h-24 overflow-y-auto">
              {filesToCommit.map((f) => (
                <div key={f.path} className="flex items-center space-x-2 text-xs font-mono text-slate-700 dark:text-zinc-300">
                  <FileCode size={13} className="text-indigo-500 shrink-0" />
                  <span className="truncate">{f.path}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">Repository Owner</label>
              <input
                type="text"
                required
                value={repoOwner}
                onChange={(e) => setRepoOwner(e.target.value)}
                placeholder="e.g. your-github-user"
                className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs font-mono text-slate-900 dark:text-white outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">Repository Name</label>
              <input
                type="text"
                required
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                placeholder="e.g. payment-service"
                className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs font-mono text-slate-900 dark:text-white outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">Base Branch</label>
              <input
                type="text"
                required
                value={baseBranch}
                onChange={(e) => setBaseBranch(e.target.value)}
                placeholder="main"
                className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs font-mono text-slate-900 dark:text-white outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">New Fix Branch</label>
              <input
                type="text"
                required
                value={targetBranch}
                onChange={(e) => setTargetBranch(e.target.value)}
                placeholder="colens/fix-sql-injection"
                className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs font-mono text-slate-900 dark:text-white outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">Commit Message</label>
            <input
              type="text"
              required
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs text-slate-900 dark:text-white outline-none focus:border-indigo-500"
            />
          </div>

          <div className="pt-2 border-t border-slate-200 dark:border-zinc-800">
            <label className="flex items-center space-x-2 cursor-pointer">
              <input
                type="checkbox"
                checked={createPR}
                onChange={(e) => setCreatePR(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300 dark:border-zinc-700"
              />
              <span className="text-xs font-semibold text-slate-800 dark:text-zinc-200">
                Automatically create Pull Request on GitHub
              </span>
            </label>
          </div>

          {createPR && (
            <div className="space-y-3 pt-1">
              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-700 dark:text-zinc-300">Pull Request Title</label>
                <input
                  type="text"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 text-xs text-slate-900 dark:text-white outline-none focus:border-indigo-500"
                />
              </div>
            </div>
          )}

          <div className="flex items-center justify-end space-x-3 pt-3 border-t border-slate-200 dark:border-zinc-800">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-slate-200 dark:border-zinc-800 text-slate-700 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-zinc-800 text-xs font-semibold transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={status === 'loading'}
              className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs flex items-center space-x-2 transition-all shadow-md cursor-pointer disabled:opacity-50"
            >
              <GitPullRequest size={14} />
              <span>{status === 'loading' ? 'Pushing to GitHub...' : createPR ? 'Push & Open PR' : 'Push Branch'}</span>
            </button>
          </div>
        </form>
      )}
    </Modal>
  );
}
