import { AnalysisResult } from '../types';

/**
 * Downloads a file with given filename and content
 */
export function downloadBlob(content: string | Blob, filename: string, mimeType: string) {
  const blob = typeof content === 'string' ? new Blob([content], { type: mimeType }) : content;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a comprehensive Markdown report from analysis
 */
export function generateMarkdownReport(analysis: AnalysisResult): string {
  const { projectName, analyzedAt, scores, issueCounts, issues, securitySummary, dependencies } = analysis;
  const dateStr = new Date(analyzedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `# 🛡️ CodeLens AI Code Health & Security Report

**Repository:** \`${projectName}\`  
**Analysis Date:** ${dateStr}  
**Overall Code Health Score:** **${scores.overall}/100**

---

## 📊 Executive Scorecard

| Dimension | Score | Rating |
| :--- | :--- | :--- |
| **Overall Health** | **${scores.overall}/100** | ${scores.overall >= 80 ? '🟢 Strong' : scores.overall >= 60 ? '🟡 Moderate Risk' : '🔴 Critical Attention'} |
| **Security & Vulnerabilities** | **${scores.security}/100** | ${scores.security >= 80 ? '🟢 Secure' : '🔴 Action Required'} |
| **Reliability & Logic** | **${scores.reliability}/100** | ${scores.reliability >= 80 ? '🟢 High' : '🟡 Needs Review'} |
| **Performance & Efficiency** | **${scores.performance}/100** | ${scores.performance >= 80 ? '🟢 Optimized' : '🟡 Bottlenecks Detected'} |
| **Maintainability & Quality** | **${scores.maintainability}/100** | ${scores.maintainability >= 80 ? '🟢 Clean' : '🟡 Technical Debt'} |
| **Architecture & Structure** | **${scores.architecture}/100** | ${scores.architecture >= 80 ? '🟢 Decoupled' : '🟡 Coupling Risks'} |

---

## 🚨 Issue Breakdown

- **Critical:** ${issueCounts.critical}
- **High:** ${issueCounts.high}
- **Medium:** ${issueCounts.medium}
- **Low:** ${issueCounts.low}
- **Informational:** ${issueCounts.info}

---

## 🔍 Detailed Findings & Recommended Fixes

${issues
  .map(
    (issue, idx) => `### ${idx + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
- **Category:** \`${issue.category}\`
- **Location:** \`${issue.file}:${issue.line}\`
- **Confidence:** ${Math.round(issue.confidence * 100)}%
${issue.cwe ? `- **CWE Tag:** \`${issue.cwe}\`` : ''}

**Description:**  
${issue.description}

${issue.whyItMatters ? `**Why It Matters:**  \n${issue.whyItMatters}\n` : ''}
${issue.recommendation ? `**Recommendation:**  \n${issue.recommendation}\n` : ''}

**Suggested Fix:**
\`\`\`
${issue.suggestedFix}
\`\`\`
`
  )
  .join('\n---\n\n')}

---

## 📦 Dependency Audits

${dependencies && dependencies.length > 0 ? `
| Package | Installed | Risk Level | Advisory |
| :--- | :--- | :--- | :--- |
${dependencies.map((d) => `| \`${d.name}\` | \`${d.version}\` | **${d.riskLevel.toUpperCase()}** | ${d.vulnerability || 'No known vulnerabilities'} |`).join('\n')}
` : 'No third-party dependency risks flagged.'}

---

*Report automatically generated by CodeLens AI Senior Reviewer Platform.*
`;
}

/**
 * Generates a clean CSV file of all detected issues
 */
export function generateCSVReport(analysis: AnalysisResult): string {
  const headers = ['ID', 'Severity', 'Category', 'Title', 'File', 'Line', 'CWE', 'Confidence', 'Description', 'Suggested Fix'];
  
  const rows = analysis.issues.map((i) => [
    `"${i.id}"`,
    `"${i.severity}"`,
    `"${i.category}"`,
    `"${i.title.replace(/"/g, '""')}"`,
    `"${i.file}"`,
    i.line,
    `"${i.cwe || 'N/A'}"`,
    `"${(i.confidence * 100).toFixed(0)}%"`,
    `"${i.description.replace(/"/g, '""')}"`,
    `"${(i.suggestedFix || '').replace(/"/g, '""')}"`,
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

/**
 * Generates a self-contained, standalone styled HTML report
 */
export function generateStandaloneHTMLReport(analysis: AnalysisResult): string {
  const { projectName, analyzedAt, scores, issueCounts, issues } = analysis;
  const dateStr = new Date(analyzedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CodeLens AI Audit - ${projectName}</title>
  <style>
    :root {
      --bg: #09090b;
      --card: #18181b;
      --border: #27272a;
      --text: #f4f4f5;
      --muted: #a1a1aa;
      --primary: #6366f1;
      --critical: #f43f5e;
      --high: #f97316;
      --medium: #eab308;
      --low: #3b82f6;
      --success: #10b981;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      padding: 32px 20px;
      line-height: 1.6;
    }
    .container { max-width: 900px; margin: 0 auto; }
    .header {
      background: var(--card);
      border: 1px solid var(--border);
      padding: 24px;
      border-radius: 16px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 16px;
    }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 9999px;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .badge-critical { background: rgba(244, 63, 94, 0.15); color: var(--critical); border: 1px solid rgba(244, 63, 94, 0.3); }
    .badge-high { background: rgba(249, 115, 22, 0.15); color: var(--high); border: 1px solid rgba(249, 115, 22, 0.3); }
    .badge-medium { background: rgba(234, 179, 8, 0.15); color: var(--medium); border: 1px solid rgba(234, 179, 8, 0.3); }
    .badge-low { background: rgba(59, 130, 246, 0.15); color: var(--low); border: 1px solid rgba(59, 130, 246, 0.3); }
    .scores-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
      gap: 12px;
      margin-bottom: 24px;
    }
    .score-card {
      background: var(--card);
      border: 1px solid var(--border);
      padding: 16px;
      border-radius: 12px;
      text-align: center;
    }
    .score-val { font-size: 24px; font-weight: 800; color: var(--primary); }
    .score-lbl { font-size: 11px; text-transform: uppercase; color: var(--muted); margin-top: 4px; font-weight: 600; }
    .section-title { font-size: 18px; font-weight: 700; margin: 24px 0 12px 0; }
    .issue-card {
      background: var(--card);
      border: 1px solid var(--border);
      padding: 20px;
      border-radius: 12px;
      margin-bottom: 16px;
    }
    .issue-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; flex-wrap: wrap; gap: 8px; }
    .issue-title { font-size: 15px; font-weight: 600; }
    .issue-loc { font-family: monospace; font-size: 12px; color: var(--muted); }
    .issue-desc { font-size: 13px; color: #d4d4d8; margin: 8px 0; }
    .code-box {
      background: #000;
      border: 1px solid #27272a;
      border-radius: 8px;
      padding: 12px;
      font-family: monospace;
      font-size: 12px;
      color: #34d399;
      overflow-x: auto;
      margin-top: 10px;
      white-space: pre-wrap;
    }
    footer { text-align: center; margin-top: 40px; font-size: 12px; color: var(--muted); }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>
        <div style="font-size: 11px; text-transform: uppercase; color: #818cf8; font-weight: 700; letter-spacing: 0.1em;">
          CONFIDENTIAL CODE AUDIT
        </div>
        <h1 style="font-size: 26px; font-weight: 800; margin-top: 4px;">${projectName}</h1>
        <p style="font-size: 13px; color: #a1a1aa; margin-top: 2px;">Analyzed on ${dateStr} by CodeLens AI</p>
      </div>
      <div style="text-align: right;">
        <div style="font-size: 36px; font-weight: 900; color: #818cf8;">${scores.overall}<span style="font-size: 16px; color: #71717a;">/100</span></div>
        <div style="font-size: 11px; text-transform: uppercase; color: #a1a1aa; font-weight: 700;">Overall Health</div>
      </div>
    </div>

    <div class="scores-grid">
      <div class="score-card">
        <div class="score-val" style="color: #f43f5e;">${scores.security}</div>
        <div class="score-lbl">Security</div>
      </div>
      <div class="score-card">
        <div class="score-val" style="color: #10b981;">${scores.reliability}</div>
        <div class="score-lbl">Reliability</div>
      </div>
      <div class="score-card">
        <div class="score-val" style="color: #f59e0b;">${scores.performance}</div>
        <div class="score-lbl">Performance</div>
      </div>
      <div class="score-card">
        <div class="score-val" style="color: #818cf8;">${scores.maintainability}</div>
        <div class="score-lbl">Maintainability</div>
      </div>
      <div class="score-card">
        <div class="score-val" style="color: #a855f7;">${scores.architecture}</div>
        <div class="score-lbl">Architecture</div>
      </div>
    </div>

    <h2 class="section-title">Audit Findings (${issues.length} Issues Detected)</h2>
    ${issues
      .map(
        (issue) => `
      <div class="issue-card">
        <div class="issue-header">
          <div style="display: flex; align-items: center; gap: 8px;">
            <span class="badge badge-${issue.severity}">${issue.severity}</span>
            <span class="issue-title">${issue.title}</span>
          </div>
          <span class="issue-loc">${issue.file}:${issue.line}</span>
        </div>
        <p class="issue-desc">${issue.description}</p>
        ${issue.suggestedFix ? `<div class="code-box">${issue.suggestedFix.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>` : ''}
      </div>
    `
      )
      .join('')}

    <footer>
      Generated with CodeLens AI — Automated Senior Code Reviewer Platform
    </footer>
  </div>
</body>
</html>`;
}

/**
 * Draws and downloads a crisp PNG scorecard badge directly to canvas
 */
export function generateScorecardImage(
  analysis: AnalysisResult,
  theme: 'cyber' | 'obsidian' | 'emerald' = 'cyber'
): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      reject(new Error('Canvas context not available'));
      return;
    }

    const width = 1200;
    const height = 675; // 16:9 ratio crisp banner
    canvas.width = width;
    canvas.height = height;

    // Palette setups
    let bgGradientStart = '#09090b';
    let bgGradientEnd = '#13111c';
    let accentColor = '#6366f1';
    let accentLight = '#818cf8';

    if (theme === 'obsidian') {
      bgGradientStart = '#0f0c1b';
      bgGradientEnd = '#1d1238';
      accentColor = '#a855f7';
      accentLight = '#c084fc';
    } else if (theme === 'emerald') {
      bgGradientStart = '#061a14';
      bgGradientEnd = '#020b08';
      accentColor = '#10b981';
      accentLight = '#34d399';
    }

    // 1. Background Fill
    const bgGrad = ctx.createLinearGradient(0, 0, width, height);
    bgGrad.addColorStop(0, bgGradientStart);
    bgGrad.addColorStop(1, bgGradientEnd);
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, width, height);

    // 2. Subtle Grid overlay
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.04)';
    ctx.lineWidth = 1;
    const gridSize = 40;
    for (let x = 0; x < width; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y < height; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    // 3. Glowing Ambient Blobs
    const blobGrad = ctx.createRadialGradient(width * 0.25, height * 0.5, 10, width * 0.25, height * 0.5, 300);
    blobGrad.addColorStop(0, 'rgba(99, 102, 241, 0.18)');
    blobGrad.addColorStop(1, 'rgba(0, 0, 0, 0)');
    ctx.fillStyle = blobGrad;
    ctx.fillRect(0, 0, width, height);

    // 4. Outer Border
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.12)';
    ctx.lineWidth = 2;
    ctx.strokeRect(30, 30, width - 60, height - 60);

    // 5. Header: Logo & Title
    ctx.fillStyle = accentLight;
    ctx.font = 'bold 16px "SF Pro Display", -apple-system, sans-serif';
    ctx.fillText('CODELENS AI • SENIOR CODE REVIEW AUDIT', 60, 80);

    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 38px "SF Pro Display", -apple-system, sans-serif';
    ctx.fillText(analysis.projectName, 60, 130);

    const dateStr = new Date(analysis.analyzedAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
    ctx.fillStyle = '#a1a1aa';
    ctx.font = '16px monospace';
    ctx.fillText(`Audited on ${dateStr}  •  ${analysis.totalFiles} Files  •  ${analysis.totalLines.toLocaleString()} Lines`, 60, 165);

    // 6. Score Circle (Left-Center)
    const centerX = 260;
    const centerY = 390;
    const radius = 130;

    // Outer track
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, 0, Math.PI * 2);
    ctx.strokeStyle = '#27272a';
    ctx.lineWidth = 18;
    ctx.stroke();

    // Health Arc
    const scoreFrac = Math.min(Math.max(analysis.scores.overall / 100, 0), 1);
    const startAngle = -Math.PI / 2;
    const endAngle = startAngle + scoreFrac * Math.PI * 2;

    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, startAngle, endAngle);
    ctx.strokeStyle = accentLight;
    ctx.lineWidth = 18;
    ctx.lineCap = 'round';
    ctx.stroke();

    // Score Text Inside Circle
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 64px "SF Pro Display", -apple-system, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(`${analysis.scores.overall}`, centerX, centerY + 12);

    ctx.fillStyle = '#a1a1aa';
    ctx.font = 'bold 14px monospace';
    ctx.fillText('/ 100 HEALTH', centerX, centerY + 45);

    // 7. Right Metrics Grid
    ctx.textAlign = 'left';
    const startX = 480;
    const metricsY = 220;

    const subMetrics = [
      { name: 'Security & Auth', score: analysis.scores.security, color: '#f43f5e' },
      { name: 'Reliability & Bugs', score: analysis.scores.reliability, color: '#10b981' },
      { name: 'Performance & Leaks', score: analysis.scores.performance, color: '#f59e0b' },
      { name: 'Maintainability', score: analysis.scores.maintainability, color: '#818cf8' },
      { name: 'Architecture Coupling', score: analysis.scores.architecture, color: '#a855f7' },
    ];

    subMetrics.forEach((m, idx) => {
      const y = metricsY + idx * 62;
      // Label
      ctx.fillStyle = '#e4e4e7';
      ctx.font = '600 17px "SF Pro Display", -apple-system, sans-serif';
      ctx.fillText(m.name, startX, y);

      // Score
      ctx.fillStyle = m.color;
      ctx.font = 'bold 18px monospace';
      ctx.fillText(`${m.score}/100`, startX + 530, y);

      // Progress bar background
      ctx.fillStyle = '#27272a';
      ctx.fillRect(startX, y + 10, 600, 8);

      // Progress bar fill
      ctx.fillStyle = m.color;
      ctx.fillRect(startX, y + 10, (600 * m.score) / 100, 8);
    });

    // 8. Bottom Bar: Issues Summary
    const footerY = 590;
    ctx.fillStyle = '#18181b';
    ctx.fillRect(60, 530, width - 120, 75);
    ctx.strokeStyle = '#27272a';
    ctx.lineWidth = 1;
    ctx.strokeRect(60, 530, width - 120, 75);

    ctx.fillStyle = '#f43f5e';
    ctx.font = 'bold 16px monospace';
    ctx.fillText(`🚨 ${analysis.issueCounts.critical} CRITICAL`, 90, 574);

    ctx.fillStyle = '#f97316';
    ctx.font = 'bold 16px monospace';
    ctx.fillText(`⚠️ ${analysis.issueCounts.high} HIGH`, 310, 574);

    ctx.fillStyle = '#eab308';
    ctx.font = 'bold 16px monospace';
    ctx.fillText(`⚡ ${analysis.issueCounts.medium} MEDIUM`, 510, 574);

    ctx.fillStyle = '#10b981';
    ctx.font = 'bold 16px monospace';
    ctx.fillText(`✅ AI FIXES READY`, 750, 574);

    ctx.fillStyle = '#71717a';
    ctx.font = '12px monospace';
    ctx.textAlign = 'right';
    ctx.fillText('VERIFIED BY CODELENS', width - 90, 574);

    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob);
      } else {
        reject(new Error('Failed to generate canvas image blob'));
      }
    }, 'image/png');
  });
}
